version: "3"

volumes:
  letsencrypt:
    external: true

networks:
  default:
    external:
      name: tccg-network

services:
  web-app:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx/app/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/app/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/app/html/mis-secretariat:/usr/share/nginx/html/mis-secretariat:ro
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.77.0.20:12201"
        tag: web-app
    environment:
      - NGINX_HOST=mis.secretariat.taichung.gov.tw
      - NGINX_PORT=80
    container_name: web-app
    
  web-api:
    image: nginx:alpine
    ports:
      - "443:443"
    links:
      - php-fpm
      - swagger-ui
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - letsencrypt:/etc/letsencrypt:ro
#      - ./nginx/api/certs:/etc/nginx/certs:ro
      - ./nginx/api/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/api/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/api/html/api:/usr/share/nginx/html/api
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.77.0.20:12201"
        tag: web-api
    environment:
      - NGINX_HOST=api.secret.taichung.gov.tw
      - NGINX_PORT=443
    container_name: web-api

  php-fpm:
    build: ./php-fpm
    image: ar0660/php:latest
    links:
      - mariadb:db
      - redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
      - ./nginx/api/html/api:/var/www/html
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.77.0.20:12201"
        tag: php-fpm
    container_name: php-fpm

  redis:
    image: redis:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./redis/data:/data
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.77.0.20:12201"
        tag: redis
    container_name: redis

  mariadb:
    image: mariadb:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mariadb/mysql:/var/lib/mysql
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.77.0.20:12201"
        tag: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    container_name: mariadb
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
      - vnc
    volumes:
      - /etc/localtime:/etc/localtime:ro
    container_name: phpmyadmin

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - API_URL=https://api.secret.taichung.gov.tw/swagger.json
    container_name: swagger-ui

  vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "5487:5900"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VNC_PASSWORD=password
    container_name: vnc
