version: "3"

networks:
  default:
    external:
      name: tccg-network

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    links:
      - logstash
    depends_on:
      - logstash
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    container_name: elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.1
    networks:
      default:
        ipv4_address: 10.77.0.20
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    container_name: logstash

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.1
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./kibana/config/:/usr/share/kibana/config:ro
    container_name: kibana
